[package]
name = "day11part2"
version = "0.1.0"
authors = ["Indragie Karunaratne <i@indragie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
